apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-demo-web-template
  labels:
    app: web-server
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"/><title>devops-demo web</title></head>
      <body>
        <h1>devops-demo web</h1>
        <p>pod-ip: ${POD_IP}</p>
        <p>serving-host: ${SERVING_HOST}</p>
      </body>
    </html>
